version: "4"
services:
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  api:
    container_name: api-container
    build: .
    image: node:14
    working_dir: /usr/src/lu-bank
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/lu-bank
    volumes:
      - ./dist/:/usr/src/lu-bank/dist/     
      - ./package.json:/usr/src/lu-bank/package.json
    ports:
      - "5050:5050"  
      - "9222:9222"
    links:
      - mongo